baseURL = "https://baoheo-12345.github.io/"
languageCode = "vi-vn"
title = "Blog Láº­p TrÃ¬nh"
theme = "PaperMod"



[pagination]
  pagerSize = 10


[params]
  env = "production"
  defaultTheme = "light"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true

  homeInfoParams.Title = "ğŸ‘‹ ChÃ o má»«ng Ä‘áº¿n vá»›i Blog Láº­p TrÃ¬nh"
  homeInfoParams.Content = """
  ÄÃ¢y lÃ  blog chia sáº» kiáº¿n thá»©c **Java & JavaScript**  
  PhÃ¹ há»£p cho sinh viÃªn vÃ  ngÆ°á»i má»›i báº¯t Ä‘áº§u há»c láº­p trÃ¬nh.
  """

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/baoheo-12345"

[menu]

  [[menu.main]]
    name = "ğŸ  Trang chá»§"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "ğŸ“ Blog"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "ğŸ‘¤ Profile"
    url = "/about/"
    weight = 3
